"""Inicial

Revision ID: e1b6329fdc57
Revises: 
Create Date: 2025-09-20 16:21:52.139236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b6329fdc57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CategoriaFAQ_id'), table_name='CategoriaFAQ')
    op.drop_table('CategoriaFAQ')
    op.drop_index(op.f('ix_Direccion_id'), table_name='Direccion')
    op.drop_table('Direccion')
    op.drop_index(op.f('ix_Sucursal_id'), table_name='Sucursal')
    op.drop_table('Sucursal')
    op.drop_index(op.f('ix_Pago_id'), table_name='Pago')
    op.drop_table('Pago')
    op.drop_index(op.f('ix_Ticket_id'), table_name='Ticket')
    op.drop_table('Ticket')
    op.drop_index(op.f('ix_Comuna_id'), table_name='Comuna')
    op.drop_table('Comuna')
    op.drop_index(op.f('ix_Rol_id'), table_name='Rol')
    op.drop_index(op.f('ix_Rol_nombre'), table_name='Rol')
    op.drop_table('Rol')
    op.drop_index(op.f('ix_FAQ_id'), table_name='FAQ')
    op.drop_table('FAQ')
    op.drop_index(op.f('ix_MedioPago_id'), table_name='MedioPago')
    op.drop_table('MedioPago')
    op.drop_index(op.f('ix_Cupon_id'), table_name='Cupon')
    op.drop_table('Cupon')
    op.drop_table('DetallePedido')
    op.drop_index(op.f('ix_Oferta_id'), table_name='Oferta')
    op.drop_table('Oferta')
    op.drop_index(op.f('ix_Usuario_email'), table_name='Usuario')
    op.drop_index(op.f('ix_Usuario_id'), table_name='Usuario')
    op.drop_table('Usuario')
    op.drop_index(op.f('ix_Producto_id'), table_name='Producto')
    op.drop_index(op.f('ix_Producto_sku'), table_name='Producto')
    op.drop_table('Producto')
    op.drop_index(op.f('ix_EstadoTicket_estado'), table_name='EstadoTicket')
    op.drop_table('EstadoTicket')
    op.drop_table('InventarioSucursal')
    op.drop_index(op.f('ix_Region_id'), table_name='Region')
    op.drop_table('Region')
    op.drop_index(op.f('ix_Pedido_id'), table_name='Pedido')
    op.drop_table('Pedido')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pedido',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('id_direccion', sa.INTEGER(), nullable=True),
    sa.Column('subtotal', sa.INTEGER(), nullable=True),
    sa.Column('total', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_direccion'], ['Direccion.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Pedido_id'), 'Pedido', ['id'], unique=False)
    op.create_table('Region',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Region_id'), 'Region', ['id'], unique=False)
    op.create_table('InventarioSucursal',
    sa.Column('sucursal_id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('ultima_modificacion', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['Producto.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['Sucursal.id'], ),
    sa.PrimaryKeyConstraint('sucursal_id', 'producto_id')
    )
    op.create_table('EstadoTicket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EstadoTicket_estado'), 'EstadoTicket', ['estado'], unique=1)
    op.create_table('Producto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=12), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('precio', sa.INTEGER(), nullable=False),
    sa.Column('added', sa.DATE(), nullable=False),
    sa.Column('ultima_modificacion', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Producto_sku'), 'Producto', ['sku'], unique=1)
    op.create_index(op.f('ix_Producto_id'), 'Producto', ['id'], unique=False)
    op.create_table('Usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('nombres', sa.VARCHAR(length=100), nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Usuario_id'), 'Usuario', ['id'], unique=False)
    op.create_index(op.f('ix_Usuario_email'), 'Usuario', ['email'], unique=False)
    op.create_table('Oferta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=False),
    sa.Column('porcentaje', sa.INTEGER(), nullable=True),
    sa.Column('valor', sa.INTEGER(), nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Oferta_id'), 'Oferta', ['id'], unique=False)
    op.create_table('DetallePedido',
    sa.Column('pedido_id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['Pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['Producto.id'], ),
    sa.PrimaryKeyConstraint('pedido_id', 'producto_id')
    )
    op.create_table('Cupon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=12), nullable=False),
    sa.Column('procentaje', sa.INTEGER(), nullable=True),
    sa.Column('valor', sa.INTEGER(), nullable=True),
    sa.Column('compra_minima', sa.INTEGER(), nullable=True),
    sa.Column('usos_maximos', sa.INTEGER(), nullable=False),
    sa.Column('usos_hechos', sa.INTEGER(), nullable=False),
    sa.Column('vigente', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Cupon_id'), 'Cupon', ['id'], unique=False)
    op.create_table('MedioPago',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MedioPago_id'), 'MedioPago', ['id'], unique=False)
    op.create_table('FAQ',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), nullable=False),
    sa.Column('pregunta', sa.VARCHAR(length=100), nullable=False),
    sa.Column('resumen', sa.VARCHAR(length=100), nullable=False),
    sa.Column('respuesta', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['CategoriaFAQ.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FAQ_id'), 'FAQ', ['id'], unique=False)
    op.create_table('Rol',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Rol_nombre'), 'Rol', ['nombre'], unique=1)
    op.create_index(op.f('ix_Rol_id'), 'Rol', ['id'], unique=False)
    op.create_table('Comuna',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_region', sa.INTEGER(), nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['Region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Comuna_id'), 'Comuna', ['id'], unique=False)
    op.create_table('Ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_estado', sa.INTEGER(), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('fecha_ingreso', sa.DATE(), nullable=False),
    sa.Column('resumen', sa.VARCHAR(length=100), nullable=False),
    sa.Column('texto', sa.TEXT(), nullable=False),
    sa.Column('ultima_modificacion', sa.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['EstadoTicket.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ticket_id'), 'Ticket', ['id'], unique=False)
    op.create_table('Pago',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_pedido', sa.INTEGER(), nullable=True),
    sa.Column('id_medio', sa.INTEGER(), nullable=True),
    sa.Column('total', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_medio'], ['MedioPago.id'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['Pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Pago_id'), 'Pago', ['id'], unique=False)
    op.create_table('Sucursal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_comuna', sa.INTEGER(), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=8, scale=6), nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=12), nullable=False),
    sa.ForeignKeyConstraint(['id_comuna'], ['Comuna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sucursal_id'), 'Sucursal', ['id'], unique=False)
    op.create_table('Direccion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('id_comuna', sa.INTEGER(), nullable=True),
    sa.Column('calle', sa.VARCHAR(length=100), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=50), nullable=False),
    sa.Column('comentario', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_comuna'], ['Comuna.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Direccion_id'), 'Direccion', ['id'], unique=False)
    op.create_table('CategoriaFAQ',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CategoriaFAQ_id'), 'CategoriaFAQ', ['id'], unique=False)
    # ### end Alembic commands ###
